# Generated by Django 2.2.9 on 2020-04-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='author',
            name='rate',
            field=models.SmallIntegerField(default=0),
        ),
    ]
