# Generated by Django 2.2.9 on 2020-04-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200418_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='author',
            name='rate',
        ),
    ]
